name: pu_watch
description: Every PU becomes a live broadcaster for transparent elections.
publish_to: 'none'
version: 1.0.0+97
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.29.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.0.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
dev_dependencies:
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
flutter:
  uses-material-design: true
  assets:
    - assets/data/pu_sample.json
    - assets/data/states_index.json
    - assets/data/states/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/pu_icon.png"
  min_sdk_android: 21
